#ifndef TOKEN_H

#define TOKEN_H 
#include  <string>


struct TOKEN
{
    enum OPERATORS {
    PLUS_OPERATOR ,
    MINUS_OPERATOR,
    MULTIPLY_OPERATOR,
    DIVIDE_OPERATOR,
    AND_OPERATOR,
    OR_OPERATOR,
    NOT_OPERATOR,
    BIT_AND_OPERATOR,
    BIT_OR_OPERATOR,
    BIT_NOT_OPERATOR,
    BIGGER_OPERATOR,
    SMALLER_OPERATOR,
    LEFT_SHIT_OPERATOR,
    RIGHT_SHIT_OPERATOR,
    EQUALS_OPERATOR,
    QUESTION_OPERATOR,
    INCREMENT_OPERATOR,
    COMPARE_OPERATOR,
    DECREMENT_OPERATOR,
    UNKNOWN
};


enum TOKEN_CONCEPTS {
    NUMBER,
    OPEN_BRACKETS,
    CLOSE_BRACKETS,
    ERROR_TOKEN,
};



    TOKEN_CONCEPTS concept;
    OPERATORS op;
    double number;
};




#endif //TOKEN_H;